# Generated by Django 3.2.4 on 2023-10-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inicio_sesion',
            fields=[
                ('idUser', models.IntegerField(db_column='idUser', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=100)),
                ('name', models.CharField(db_column='name1', max_length=100)),
                ('passw', models.CharField(db_column='pasw', max_length=100)),
            ],
            options={
                'db_table': 'sesion',
            },
        ),
    ]
