# Generated by Django 3.2.4 on 2023-10-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datos',
            fields=[
                ('idUser', models.IntegerField(db_column='idUser', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('correo', models.CharField(db_column='correo', max_length=100)),
                ('edad', models.CharField(db_column='edad', max_length=100)),
                ('p1', models.CharField(db_column='pre1', max_length=100)),
                ('p2', models.CharField(db_column='pre2', max_length=100)),
                ('p3', models.CharField(db_column='pre3', max_length=100)),
                ('p4', models.CharField(db_column='pre4', max_length=100)),
                ('p5', models.CharField(db_column='pre5', max_length=100)),
                ('p6', models.CharField(db_column='pre6', max_length=100)),
                ('p7', models.CharField(db_column='pre7', max_length=100)),
                ('p8', models.CharField(db_column='pre8', max_length=100)),
            ],
            options={
                'db_table': 'datos',
            },
        ),
    ]
